apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: default
spec:
  encryptedData:
    password: AgBUPk3WfYfO00JFjQ0i1Hk5M0/yw8HjVnpu2zAVqQEZJMycMLwNQkNTcRU+npZB6Ddg/7RTa7ZeGmUcjdNcbIajLGSYz/sRyw/NlX3HEBbyvRT/Fa6ZQHXuS0c2+JkGGxhCdlLfCMtMcYg9bZNFRGpR36EX5aNrutcg6yqypoeQs1bM7KWKHC5AR9o6z4n/tlRbutHnOPyBFfeSL5HhEXTL7ayxL9E6t4JPDva8ztuOCY+QN/apMD/ih3hy/h2BEthwcW1CLMrOrp6R80VdenPheGGMnzeRfXca5KbpANbaihvuZU0/O/Nl78lEqtedKBfbwHiT8dCzvAWZ3l6C34UJakfBouTEd3yp/n2+c2QOb742VF9k7bHqRSTNH0fw9p5ZrYeBofbjBNApjDuNsi/wX66UoL2Wg+tvIGSEKJOk91PIeyqCwwQEYzpX9CsmwqY+NIyXVcMpGhROUH/yj+mEXtNpzda4qTh2B6EDX01t+8XeM78B7AlelflmcYpbgQJ6WR/pU7s66RWT7WZkgtcf+ynhsLH1TKmfLs1aVYFjyRtUjI/ns1MTQ80AhA3veLk48vCfQ8N1FSiFWX0821aMJS27avEX5YzOoRgJGzDLiOlmoI2SnsFviFrnKpMrtM54KdMD4XrUwevfOzPXGPNH3GdCYGgo1eCPvtLeQXTNP4nz8XwMq/b21k0Ytms5KqNLTs1RlyRpMck=
    user: AgBNORjB+S8Z+sAsLW3YoQJWoWVsjQfAdCGQ8Ew2jl0ZoD9LojE++blIrdVV+Ml0LjMe1WaRnX11XVg2w+9VgUwiV1xihC2cYIcwCaMBMIZmvE6qr4FZp+2V9ql0jyI7cQILpuoBwrEUyzrUCC2lCLWq/ECoozJkJV6teRIma9yWSd0Vm0JXfg5me7ki9/g+dr/hJENIqp+P15AOQqCx5kgale//BAFeDhUBNPedDkZyfsuO+Tr+uF/c6xCqeVAC+IVBKsJRguR+wsXX+M1ThucoRybSGOBSb9JrWY2hcUQ3eQrzQNvVdE0Bqfc2V5jnccDADaq5zMSqd6cmGWeLDX9mnsmfriTjU07qaWaeIbpBGpfv8OIo4+lGsUGHHR8IrWsKw7LhX1j7PnKov5S0uR7XN0yQNmY5FLEWoIdAStCZlGS3clKJGnMz7ORhgNcG1SryG8iz3mj3V8v6F8JepZym89Z7rkwftUwKX+dj4m5KmOp37j8s5mhs0H20tqOk8rV+lWDYlELinewRvmZNlszh+Lhx7tnGbompcLYHTKYiv4Hh+RmWb9zSnbUFPobVsNKFnDW9DRi3u6YNJEeXA1b1qKkQLTiO7Li217zHzhR6VriYFKn8+EMoR2CNipYC/Cysb8rran5fy5ktBvxJheAj4yQxfP7d+QIhPw6bTa7KzYNI5P3Oalcd0I7JzyylUPG3N85hAQ==
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: default
